services:

  database:
    container_name: database
    image: postgres:alpine
    env_file:
      - ../.env.example
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - server-network

  deploy:
    container_name: deploy
    build:
      context: ../server
      dockerfile: ../docker/server.Dockerfile
      target: deploy
    env_file:
      - ../.env.example
      - ../server/.env
    depends_on:
      - database
    networks:
      - server-network
    volumes:
      - ../server/src:/opt/app/src
      - ../server/prisma:/opt/app/prisma
    command: npm run prisma:deploy

volumes:
  database_data:

networks:
  server-network: